#Tacticas
Tactica.create(nombre: '4-4-2')
Tactica.create(nombre: '4-3-3')
Tactica.create(nombre: '3-4-3')

#Posiciones
Posicion.create(nombre: 'ARQ')
Posicion.create(nombre: 'DEF')
Posicion.create(nombre: 'VOL')
Posicion.create(nombre: 'DEL')

#Clubes
Club.create(nombre: 'ALDOSIVI')
Club.create(nombre: 'ARGENTINOS JUNIORS')
Club.create(nombre: 'ARSENAL')
Club.create(nombre: 'ATLÉTICO DE RAFAELA')
Club.create(nombre: 'BANFIELD')
Club.create(nombre: 'BELGRANO')
Club.create(nombre: 'BOCA JUNIORS')
Club.create(nombre: 'COLÓN')
Club.create(nombre: 'CRUCERO DEL NORTE')
Club.create(nombre: 'DEFENSA Y JUSTICIA')
Club.create(nombre: 'ESTUDIANTES LP.')
Club.create(nombre: 'GIMNASIA Y ESGRIMA LP.')
Club.create(nombre: 'GODOY CRUZ')
Club.create(nombre: 'HURACÁN')
Club.create(nombre: 'INDEPENDIENTE')
Club.create(nombre: 'LANÚS')
Club.create(nombre: 'NEWELLS OLD BOYS')
Club.create(nombre: 'NUEVA CHICAGO')
Club.create(nombre: 'OLIMPO')
Club.create(nombre: 'QUILMES')
Club.create(nombre: 'RACING')
Club.create(nombre: 'RIVER PLATE')
Club.create(nombre: 'ROSARIO CENTRAL')
Club.create(nombre: 'SAN LORENZO')
Club.create(nombre: 'SAN MARTÍN SAN JUAN')
Club.create(nombre: 'SARMIENTO')
Club.create(nombre: 'TEMPERLEY')
Club.create(nombre: 'TIGRE')
Club.create(nombre: 'UNIÓN')
Club.create(nombre: 'VÉLEZ SARSFIELD')

#Jugadores
#ALDOSIVI
#Arqueros
Jugador.create(nombre: 'BULASIO, ARIEL RAUL', club_id: 1, posicion_id: 1)
Jugador.create(nombre: 'CAMPODONICO, PABLO JAVIER', club_id: 1, posicion_id: 1)
Jugador.create(nombre: 'VEGA, MATIAS ALEJANDRO', club_id: 1, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'CANEVER, FRANCO NICOLAS', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'DIAZ, ANGEL GASTON', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'LEON, FEDERICO MATIAS', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'LEON, GONZALO EMANUEL', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'LEQUI, MATIAS EMANUEL', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'MULLER, AXEL MILTON', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'OLMOS, LUCAS', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'ORTIZ, GUILLERMO', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'QUILEZ, ISMAEL ALBERTO', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'SOTO, CARLOS DANIEL', club_id: 1, posicion_id: 2)
Jugador.create(nombre: 'VARGAS, ROQUE GABRIEL', club_id: 1, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BUSTOS, NICOLAS ALEJANDRO', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'BUZZINI, MARIANO', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'CAPURRO, ALEJANDRO RUBEN', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'FREDES, LEONARDO', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'GALVAN, JONATHAN SEABASTIAN', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'GARGIULO, JUAN PABLO', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'LAMBERTI, HERNAN AGUSTIN', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'LOPEZ, IVAN MARCELO', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'LOPEZ, ANDRES', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'MENSEGUEZ, JUAN CARLOS', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'RIVERO, MARTIN RODRIGO', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'SECCAFIEN, MARIANO ENRIQUE', club_id: 1, posicion_id: 3)
Jugador.create(nombre: 'TORO, BRIAN', club_id: 1, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CARRANZA, CESAR ALBERTO', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'DIP, DANIEL ALBERTO', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'LAGOS, DIEGO EDUARDO', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'LUGUERCIO, PABLO ARIEL', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'MARTINEZ, ROGER BEYKER', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'MIRACCO, NICOLAS JUAN MARTIN', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'ROSALES, JOSE SANTIAGO', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'SAND, JOSE GUSTAVO', club_id: 1, posicion_id: 4)
Jugador.create(nombre: 'VILDOZO, LUIS ANGEL', club_id: 1, posicion_id: 4)

#ARGENTINOS JUNIORS
#Arqueros
Jugador.create(nombre: 'CHAVES, LUCAS ABRAHAM', club_id: 2, posicion_id: 1)
Jugador.create(nombre: 'GABBARINI, ADRIAN JOSE', club_id: 2, posicion_id: 1)
Jugador.create(nombre: 'GIOVINI, SEBASTIAN MATIAS', club_id: 2, posicion_id: 1)
Jugador.create(nombre: 'OJEDA, LUIS ALBERTO', club_id: 2, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ALMANDOZ, MARIANO LUIS', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'ALVAREZ, CRISTIAN OSVALDO', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'BATISTA, NICOLAS', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'FLORES, FRANCO VALENTIN', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'FREIRE, NICOLAS OMAR', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'GARRE, ANGEL EZEQUIEL', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'LASO, JOAQUIN MARCELO', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'LEMOS, JUAN PABLO', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'MATRICARDI, PATRICIO MARTIN', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'RODRIGUEZ, LUCAS NAHUEL', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'SABIA, JUAN ALBERTO', club_id: 2, posicion_id: 2)
Jugador.create(nombre: 'TORREN, MIGUEL ANGEL', club_id: 2, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AGUERO, EMILIANO GERMAN', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'ALANIZ, DIEGO MARTIN', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'BASUALDO, GERMAN RODRIGO', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'GALLEGO, FEDERICO', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'GARCIA, MATIAS IGNACIO', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'GIMENEZ, MATIAS ALEJANDRO', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'HAM, EZEQUIEL NAIM', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'IÑIGUEZ, GASPAR EMMANUEL', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'LEDESMA, CRISTIAN RAUL', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'LENIS, REINALDO', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'TROVENTO, EMILIANO LEONEL', club_id: 2, posicion_id: 3)
Jugador.create(nombre: 'ZAPATA, MARTIN DARIO', club_id: 2, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CABRAL, LUCIANO JAVIER', club_id: 2, posicion_id: 4)
Jugador.create(nombre: 'CANO, LUCAS MATIAS', club_id: 2, posicion_id: 4)
Jugador.create(nombre: 'CASTILLEJOS, GONZALO RUBEN', club_id: 2, posicion_id: 4)
Jugador.create(nombre: 'FRANZOIA, ANDRES', club_id: 2, posicion_id: 4)
Jugador.create(nombre: 'RINALDI, LAUTARO PATRICIO', club_id: 2, posicion_id: 4)
Jugador.create(nombre: 'RODRIGUEZ, JONATHAN JOEL', club_id: 2, posicion_id: 4)

#ARSENAL SARANDÍ
#Arqueros
Jugador.create(nombre: 'ANDRADA, ESTEBAN MAXIMILIANO', club_id: 3, posicion_id: 1)
Jugador.create(nombre: 'AQUINO, MAURICIO HERNAN', club_id: 3, posicion_id: 1)
Jugador.create(nombre: 'LIMIA, OSCAR ALEJANDRO', club_id: 3, posicion_id: 1)
Jugador.create(nombre: 'MARUSSI, HECTOR ALAN', club_id: 3, posicion_id: 1)
Jugador.create(nombre: 'MOYANO, RENE DANIEL', club_id: 3, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'CASTRUCCIO, ADRIAN IVAN', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'CORREA, NICOLAS', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'CURADO, MARCOS', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'CURBELO, JORGE WINSTON', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'MILO, FEDERICO EMANUEL', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'PEREZ, DAMIAN ALFREDO', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'ROSERO, DANIEL ALEJANDRO', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'SAN ROMAN, JOSE IGNACIO', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'SARULYTE, MATIAS', club_id: 3, posicion_id: 2)
Jugador.create(nombre: 'VARGAS, IVAN ANGEL', club_id: 3, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ASPREA, TOMAS', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'CAMPOS TORO, MATIAS DANIEL', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'CARDOZO, JULIAN GABRIEL', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'CARRERA, RAMIRO ANGEL', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'CHAVEZ, CRISTIAN MANUEL', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'DE LILLO, RAMIO DAVID', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'ESMERADO, GASTON RUBEN', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'FLORES, GABRIEL ALEJANDRO', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'FREDES, HERNAN GABRIEL', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'GIMENEZ, GONZALO', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'GODOY, LEANDRO', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'MARCONE, IVAN JOSE', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'MUÑOZ, FABIAN NICOLAS', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'RUIZ, EZEQUIEL EDUARDO', club_id: 3, posicion_id: 3)
Jugador.create(nombre: 'ZALDIVIA, MATIAS EZEQUIEL', club_id: 3, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BURZIO, PABLO CESAR', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'CIACCHERI, ESTEBAN', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'COSTAS, FRANCO LAUTARO', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'HERRERA, MAXIMILIANO FRANCISCO', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'PUGH, LUCAS RAMON', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'RASIC, FEDERICO IVAN', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'SCHDMIT, CARLOS BRYAN', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'SILVA, SANTIAGO MARTIN', club_id: 3, posicion_id: 4)
Jugador.create(nombre: 'ZELAYA, EMILIO JOSE', club_id: 3, posicion_id: 4)

#ATLÉTICO DE RAFAELA
#Arqueros
Jugador.create(nombre: 'CONDE, ESTEBAN NESTOR', club_id: 4, posicion_id: 1)
Jugador.create(nombre: 'DE GIORGIS, CARLOS ALBERTO', club_id: 4, posicion_id: 1)
Jugador.create(nombre: 'ROSSETTI, GUIDO', club_id: 4, posicion_id: 1)
Jugador.create(nombre: 'WERNER, AXEL', club_id: 4, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'CANAVESSIO, NICOLAS', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'COLOMBO, RODRIGO JESUS', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'DEL GRECCO, NICOLAS', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'DIAZ, MARTIN DAMIAN', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'GOMEZ, MAURICIO SEBASTIAN', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'KRUSPZKY, LUCAS NAHUEL', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'MORALES, DIMAS EZEQUIEL', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'NIZ, ALEXIS JORGE', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'RE, GERMAN DAVID', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'SACKS, JOEL', club_id: 4, posicion_id: 2)
Jugador.create(nombre: 'SANCHEZ, SEBASTIAN FERNANDO', club_id: 4, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BASTIA, ADRIAN JESUS', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'CASTELLANO, MATEO', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'ELUCHANS, JUAN EDUARDO', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'FERNANDEZ, GUILLERMO MATIAS', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'FERREYRA, OSMAR DANIEL', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'GAITAN, PABLO LEONEL', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'GODOY, LEANDRO', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'MARINO, GUILLERMO ANDRES', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'MONTIEL, DIEGO ARMANDO', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'RODRIGUEZ ROJAS, GERMAN EZEQUIEL', club_id: 4, posicion_id: 3)
Jugador.create(nombre: 'SERRANO, WALTER OMAR', club_id: 4, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CABRAL, FACUNDO CATRIEL', club_id: 4, posicion_id: 4)
Jugador.create(nombre: 'DEPETRIS, RODRIGO LEONEL', club_id: 4, posicion_id: 4)
Jugador.create(nombre: 'GONZALEZ, FEDERICO RAFAEL', club_id: 4, posicion_id: 4)
Jugador.create(nombre: 'JOMINY, FRANCO MARCELO', club_id: 4, posicion_id: 4)
Jugador.create(nombre: 'ORSINI, NICOLAS', club_id: 4, posicion_id: 4)
Jugador.create(nombre: 'PUSETTO, IGNACIO', club_id: 4, posicion_id: 4)
Jugador.create(nombre: 'QUIROGA, MAURO DANIEL', club_id: 4, posicion_id: 4)
Jugador.create(nombre: 'SOSA, SERGIO CANDELARIO', club_id: 4, posicion_id: 4)

#BANFIELD
#Arqueros
Jugador.create(nombre: 'ALTAMIRANO, FACUNDO', club_id: 5, posicion_id: 1)
Jugador.create(nombre: 'BOLOGNA, ENRIQUE ALBERTO', club_id: 5, posicion_id: 1)
Jugador.create(nombre: 'PELLEGRINO, DIEGO FERNANDO', club_id: 5, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BETTINI, GONZALO', club_id: 5, posicion_id: 2)
Jugador.create(nombre: 'BIANCHI ARCE, NICOLAS', club_id: 5, posicion_id: 2)
Jugador.create(nombre: 'CIVELLI, LUCIANO', club_id: 5, posicion_id: 2)
Jugador.create(nombre: 'DIAZ, CRISTIAN HERNAN', club_id: 5, posicion_id: 2)
Jugador.create(nombre: 'NEGRO, GONZALO', club_id: 5, posicion_id: 2)
Jugador.create(nombre: 'NOGUERA, FABIAN ARIEL', club_id: 5, posicion_id: 2)
Jugador.create(nombre: 'RODRIGUEZ, JORGE AGUSTIN', club_id: 5, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ABELAIRAS, MATIAS ENRIQUE', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'CALZADA, MAXIMILIANO MATIAS', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'CAZARES, JUAN RAMON', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'CECCHINI, RODRIGO EMMANUEL', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'DOMINGO, NICOLAS MARIO', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'ERVITTI, WALTER DANIEL', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'REMEDI, E.', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'REQUENA, JONATHAN IVAN', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'ROSSI, IVAN JAVIER', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'VITTOR, SERGIO JAVIER', club_id: 5, posicion_id: 3)
Jugador.create(nombre: 'YERI, NAHUEL MARIANO', club_id: 5, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ASENJO, MAURICIO GABRIEL', club_id: 5, posicion_id: 4)
Jugador.create(nombre: 'CHETTI, LEANDRO ANDRES', club_id: 5, posicion_id: 4)
Jugador.create(nombre: 'CUERO, MAURICIO ANDRES', club_id: 5, posicion_id: 4)
Jugador.create(nombre: 'GARCIA, JUAN EZEQUIEL', club_id: 5, posicion_id: 4)
Jugador.create(nombre: 'MOLINA, CRISTIAN', club_id: 5, posicion_id: 4)
Jugador.create(nombre: 'NOIR, RICARDO DANIEL', club_id: 5, posicion_id: 4)
Jugador.create(nombre: 'TRINIDAD, ENZO GABRIEL', club_id: 5, posicion_id: 4)
Jugador.create(nombre: 'VIATRI, LUCAS EZEQUIEL', club_id: 5, posicion_id: 4)

#BELGRANO
#Arqueros
Jugador.create(nombre: 'ACOSTA, LUCAS MAURICIO', club_id: 6, posicion_id: 1)
Jugador.create(nombre: 'BONANSEA, FEDERICO', club_id: 6, posicion_id: 1)
Jugador.create(nombre: 'HEREDIA, PABLO NICOLAS', club_id: 6, posicion_id: 1)
Jugador.create(nombre: 'OLAVE, JUAN CARLOS', club_id: 6, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ALVAREZ, FEDERICO HERNAN', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'BARRIOS, PIER MIQUEAS', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'ESCUDERO, SERGIO DANIEL', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'ESPINDOLA LOPEZ, ESTEBAN EZEQUIEL', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'FERREYRA, NICOLAS AGUSTIN', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'LEMA, CRISTIAN FRANCO', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'MATTALIA, PABLO', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'PEREZ, CLAUDIO DANIEL', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'SARAVIA, RENZO', club_id: 6, posicion_id: 2)
Jugador.create(nombre: 'TURUS, GASTON ALEJANDRO', club_id: 6, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ALANIS, GABRIEL GUSTAVO', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'COCHIS, GERMAN GABRIEL', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'ESTEVENAUX, IVAN', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'FARRE, GUILLERMO MARTIN', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'GIORDANA, SANTIAGO', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'GONZALEZ, ESTEBAN NICOLAS', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'MANZANELLI, OSVALDO CESAR', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'PARODI, LUCAS JOAQUIN', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'PREDIGUER, LEONARDO SEBASTIAN', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'RIGONI, EMILIANO ARIEL', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'VELAZQUEZ, JORGE LUIS', club_id: 6, posicion_id: 3)
Jugador.create(nombre: 'ZELARRAYAN, LUCAS NAHUEL', club_id: 6, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BENGTON, JERRY RICARDO', club_id: 6, posicion_id: 4)
Jugador.create(nombre: 'LUJAN, ISAIAS NAHUEL', club_id: 6, posicion_id: 4)
Jugador.create(nombre: 'MARQUEZ, FERNANDO ANDRES', club_id: 6, posicion_id: 4)
Jugador.create(nombre: 'OBOLO, MAURO IVAN', club_id: 6, posicion_id: 4)
Jugador.create(nombre: 'VALDEMARIN, JOEL', club_id: 6, posicion_id: 4)
Jugador.create(nombre: 'ZARATE, MAXIMILIANO', club_id: 6, posicion_id: 4)

#BOCA JUNIORS
#Arqueros
Jugador.create(nombre: 'ORION, AGUSTIN IGNACIO', club_id: 7, posicion_id: 1)
Jugador.create(nombre: 'SARA, GUILLERMO', club_id: 7, posicion_id: 1)
Jugador.create(nombre: 'TRIPODI, EMANUEL', club_id: 7, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BRAVO, FEDERICO', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'BURDISSO, GUILLERMO ENIO', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'DIAZ, DANIEL ALBERTO', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'KOMAR, JUAN CRUZ', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'MAGALLAN, LISANDRO', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'MARIN, LUCAS LEANDRO', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'MONZON, LUCIANO FABIAN', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'PERUZZI, GINO', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'ROLIN, GERMAN ALEXIS', club_id: 7, posicion_id: 2)
Jugador.create(nombre: 'TORSIGLIERI, MARCO NATANEL', club_id: 7, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BETANCUR, RODRIGO', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'CARRIZO, FEDERICO GASTON', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'CASTELLANI, GONZALO PABLO', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'COLAZO, NICOLAS CARLOS', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'CRISTALDO, FRANCO SEBASTIAN', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'CUBAS, ADRIAN ANDRES', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'ERBES, CRISTIAN DAMIAN', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'FUENZALIDA, JOSE PEDRO', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'GAGO, FERNANDO RUBEN', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'LODEIRO, MARCELO NICOLAS', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'MELI, CESAR MARCELO', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'PEREZ, PABLO JAVIER', club_id: 7, posicion_id: 3)
Jugador.create(nombre: 'POCCHETINO, TOMAS', club_id: 7, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CALLERI, JONATHAN', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'CHAVEZ, ANDRES ELISEO', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'DALLA COSTA, MAURO DANIEL', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'MARTINEZ, JUAN MANUEL', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'OSVALDO, PABLO DANIEL', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'PALACIOS, SEBASTIAN ALBERTO', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'PAVON, CRISTIAN DAVID', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'TEVEZ, CARLOS ALBERTO', club_id: 7, posicion_id: 4)
Jugador.create(nombre: 'VADALA, GUIDO NAHUEL', club_id: 7, posicion_id: 4)


#COLÓN
#Arqueros
Jugador.create(nombre: 'BROUN, JORGE EMANUEL', club_id: 8, posicion_id: 1)
Jugador.create(nombre: 'LOVERA, IGNACIO', club_id: 8, posicion_id: 1)
Jugador.create(nombre: 'MEHRING, ANDRES', club_id: 8, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BITTOLO, MARIANO EZEQUIEL', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'CASTILLO, LUIS LEANDRO', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'CONTI, GERMAN ANDRES', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'CUEVAS, PABLO SEBASTIAN', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'FERRACUTTI, GUILLERMO', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'GARCIA, EMILIANO MARTIN', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'LANDA, LUCAS LEON', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'LAZZARONI, FRANCO MARTIN', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'MARTINEZ, MAXIMILIANO JOSE', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'RODRIGUEZ, CLEMENTE JUAN', club_id: 8, posicion_id: 2)
Jugador.create(nombre: 'SAIN, CRISTIAN CARLOS IVAN', club_id: 8, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BALLINI, MATIAS LEONEL', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'CASADO, VICTOR EMANUEL', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'COMACHI, LUCAS', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'EGUREN, SEBASTIAN', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'FERNANDEZ, MARCOS GABRIEL', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'FILIPPI, FRANCISCO', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'GARNIER, LUIS YAMIL', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'LEDESMA, PABLO MARTIN', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'LEYS, FRANCO EZEQUIEL', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'LLAMA, CRISTIAN EZEQUIEL', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'PEREZ, DANIEL', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'POBLETE, GERONIMO GASTON', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'RAMIREZ, DAVID ARTURO', club_id: 8, posicion_id: 3)
Jugador.create(nombre: 'ROMERO, BRAIAN EZEQUIEL', club_id: 8, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BECERRA, RAUL OSCAR', club_id: 8, posicion_id: 4)
Jugador.create(nombre: 'BELINETZ, OSCAR HECTOR', club_id: 8, posicion_id: 4)
Jugador.create(nombre: 'GARCIA, CRISTIAN ANDRES', club_id: 8, posicion_id: 4)
Jugador.create(nombre: 'GOMEZ, EXEQUIEL MAXIMILIANO', club_id: 8, posicion_id: 4)
Jugador.create(nombre: 'GUANCA, CRISTIAN DAVID', club_id: 8, posicion_id: 4)
Jugador.create(nombre: 'VILLARRUEL, GUSTAVO ALEJANDRO', club_id: 8, posicion_id: 4)

#CRUCERO DEL NORTE
#Arqueros
Jugador.create(nombre: 'CAFFA, GERMAN MARTIN', club_id: 9, posicion_id: 1)
Jugador.create(nombre: 'MENDONCA, JUAN IGNACIO', club_id: 9, posicion_id: 1)
Jugador.create(nombre: 'RAMIREZ, HORACIO MARTIN', club_id: 9, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BAREYRO, DANTE NESTOR', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'BARRAZA, JULIO EDUARDO', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'CABAÑA, VICOR OSCAR', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'CABRERA, JUAN ALBERTO', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'DE MATTEI, NICOLAS DIEGO', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'LECHNER, RODRIGO NICOLAS', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'OLIVA, MAXIMILIANO FERNANDO', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'PEREZ, DANIEL ALEJANDRO', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'ROSSO, FEDERICO GUILLERMO', club_id: 9, posicion_id: 2)
Jugador.create(nombre: 'TOMASSINI, GABRIEL', club_id: 9, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'CABALLERO, LUCAS IVAN', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'CHIRONI, GABRIEL', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'DUJAUT, JOSE', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'FILEPPI, CLAUDIO JULIO', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'LAMAS, MARCELO ALEJANDRO', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'MARTINEZ, ALEJANDRO NICOLAS', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'MELGAREJO, EDGAR DAMIAN', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'MONSERRAT, FABIAN ARIEL', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'OLMEDO, NICOLAS ANDRES', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'RIVAS, MAURICIO', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'ROMERO, DARDO GUIDO', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'TORRES, DIEGO ALBERTO', club_id: 9, posicion_id: 3)
Jugador.create(nombre: 'VAZQUEZ, FABIO FRANCISCO', club_id: 9, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ALVAREZ, ERNESTO FRANCISCO', club_id: 9, posicion_id: 4)
Jugador.create(nombre: 'AVALOS, GABRIEL', club_id: 9, posicion_id: 4)
Jugador.create(nombre: 'COLZERA, ARIEL DAMIAN', club_id: 9, posicion_id: 4)
Jugador.create(nombre: 'MOLINAS, IVAN ALEJANDRO', club_id: 9, posicion_id: 4)
Jugador.create(nombre: 'STUPISKI, PABLO MATIAS', club_id: 9, posicion_id: 4)
Jugador.create(nombre: 'YAGUZIECKO, ADRIAN AGUSTIN', club_id: 9, posicion_id: 4)

#DEFENSA Y JUSTICIA
#Arqueros
Jugador.create(nombre: 'ARIAS, GABRIEL', club_id: 10, posicion_id: 1)
Jugador.create(nombre: 'DOBBOLETTA, JUAN IGNACIO', club_id: 10, posicion_id: 1)
Jugador.create(nombre: 'SANTILLO, PABLO ARIEL', club_id: 10, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BENITEZ, MARCELO NICOLAS', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'FACCIOLI, EMIR SAUL', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'GAMARRA, MARCELO ADRIAN', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'MARTINEZ, DAMIAN ALBERTO', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'MATHEU, CARLOS JAVIER', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'MAYA, FEDERICO', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'SAVELJICH, ESTEBAN ARIEL', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'TEJERA, JUAN ANDRES', club_id: 10, posicion_id: 2)
Jugador.create(nombre: 'VELLA, LUCIANO GERMAN', club_id: 10, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ACEVEDO, WALTER ANIBAL', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'ALVAREZ, FABIO RAMIRO', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'BERTOCCHI, MIGUEL NICOLAS', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'BUSSE, WALTER ALEJANDRO', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'CABRERA, GONZALO GABRIEL', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'CASSOROTTI, J.', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'JUAREZ, AXEL FERNANDO', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'LEYES, NERY', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'RIVERO, JOSE IGNACIO', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'TELLECHEA, EMILIANO MATHIAS', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'TONETTO, DIEGO RUBEN', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'VENTURI, DIEGO SEBASTIAN', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'YACOB, DIEGO HERNAN', club_id: 10, posicion_id: 3)
Jugador.create(nombre: 'YACUZZI, JAVIER ORLANDO', club_id: 10, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BARBIERI, MARIANO OMAR', club_id: 10, posicion_id: 4)
Jugador.create(nombre: 'CURUCHET, FACUNDO NICOLAS', club_id: 10, posicion_id: 4)
Jugador.create(nombre: 'DAL CASON, GUIDO WALTER', club_id: 10, posicion_id: 4)
Jugador.create(nombre: 'FERNANDEZ, NICOLAS EMANNUEL', club_id: 10, posicion_id: 4)
Jugador.create(nombre: 'ISNALDO, EUGENIO HORACIO', club_id: 10, posicion_id: 4)
Jugador.create(nombre: 'RIUS ARAGALLO, CIRO PABLO', club_id: 10, posicion_id: 4)
Jugador.create(nombre: 'RODRIGUEZ, JULIO CESAR', club_id: 10, posicion_id: 4)
Jugador.create(nombre: 'SANCHEZ SOTELO, JUAN IGNACIO', club_id: 10, posicion_id: 4)

#ESTUDIANTES LP.
#Arqueros
Jugador.create(nombre: 'ANDUJAR, FACUNDO ALONSO', club_id: 11, posicion_id: 1)
Jugador.create(nombre: 'NAVARRO, HILARIO BERNARDO', club_id: 11, posicion_id: 1)
Jugador.create(nombre: 'ROSSI, AGUSTIN DANIEL', club_id: 11, posicion_id: 1)
Jugador.create(nombre: 'RUSTTON, LAUREANO', club_id: 11, posicion_id: 1)
Jugador.create(nombre: 'SILVA, AGUSTIN', club_id: 11, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'AGUIRREGARAY, MATIAS', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'AYALA, RODRIGO ELVIO', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'BRITO, MAURO NICOLAS', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'DELGADO, RAFAEL MARCELO', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'DESABATO, LEANDRO', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'DOMINGUEZ, SEBASTIAN ENRIQUE', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'DOMIZZI, STEFANO', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'JARA, LEONARDO RAFAEL', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'MENA, CESAR AUGUSTO', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'PEREIRA, ALVARO DANIEL', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'PRESENTADO, MATIAS ISIDORO', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'ROSALES, PABLO MAURICIO', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'SCHUNKE, JONATHAN', club_id: 11, posicion_id: 2)
Jugador.create(nombre: 'VARGAS, LUCIANO ANDRES', club_id: 11, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ACOSTA, LUCIANO FEDERICO', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'AUZQUI, CARLOS DANIEL', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'BARBONA, DAVID MATIAS', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'DAMONTE, ISRAEL ALEJANDRO', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'GIL, LEONARDO ROQUE ALBANO', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'GIL ROMERO, GASTON', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'MARCHIONI, JULIAN AUGUSTO', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'MARQUEVICH, NICOLAS ANIBAL', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'MARTINEZ, ROMAN FERNANDO', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'ORIHUELA, MATIAS', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'SANCHEZ MIÑO, JUAN MANUEL', club_id: 11, posicion_id: 3)
Jugador.create(nombre: 'SEIJAS, GABRIEL NICOLAS', club_id: 11, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ANSELMO, FEDERICO MARCELO', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'CACERES, ISIDRO ALBERTO', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'CARRILLO, GUIDO MARCELO', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'CERUTTI, EZEQUIEL', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'MENDOZA, DIEGO ROBERTO', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'MIRANDA, EZEQUIEL', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'QUINTANA, FACUNDO NICOLAS', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'ROSSO, MATIAS GABRIEL', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'SANDOVAL, CARLOS LEANDRO', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'UMERE, ELIAS', club_id: 11, posicion_id: 4)
Jugador.create(nombre: 'VERA, DIEGO DANIEL', club_id: 11, posicion_id: 4)

#GIMNASIA Y ESGRIMA LP.
#Arqueros
Jugador.create(nombre: 'BONNIN, YAIR JAVIER', club_id: 12, posicion_id: 1)
Jugador.create(nombre: 'MARTINARIAS, ALEXIS', club_id: 12, posicion_id: 1)
Jugador.create(nombre: 'NAVARRO, NICOLAS GASTON', club_id: 12, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BARSOTTINI, OSVALDO RUBEN', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'BENITEZ, OLIVIER', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'CORONEL, MAXIMILIANO', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'GUANINI, MANUEL', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'JAUREGUI, IGNACIO', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'LICHT, LUCAS MATIAS', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'OREJA, FACUNDO JULIAN', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'POCHOLO, JUAN PABLO', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'URQUIZA, FACUNDO', club_id: 12, posicion_id: 2)
Jugador.create(nombre: 'VELAZQUEZ, SERGIO EZEQUIEL', club_id: 12, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ANDRADA, OMAR BIRAN', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'BONIFACIO, EZEQUIEL', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'BRUM, ROBERTO SEBASTIAN', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'DELGADO, AUGUSTO CRUZ', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'FERNANDEZ, IGNACIO MARTIN', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'FERNANDEZ, ALVARO', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'GARCIA, ARIEL MATIAS', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'GORGERINO, MAXIMILIANO DANIEL', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'LACHALDE, IGNACIO', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'LUGONES, ALEJANDRO ADRIAN', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'MENDOZA, JAVIER OSVALDO', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'NICOLAIEVSKY, DIEGO OSCAR', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'NOBLE, MATIAS JESUS', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'POUSO, OMAR HEBER', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'ROJAS, JORGE LUIS', club_id: 12, posicion_id: 3)
Jugador.create(nombre: 'SILVA, JUAN IGNACIO', club_id: 12, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BOU, WALTER ARIEL', club_id: 12, posicion_id: 4)
Jugador.create(nombre: 'CONTIN, LEANDRO NICOLAS', club_id: 12, posicion_id: 4)
Jugador.create(nombre: 'CONTRERAS, RODRIGO', club_id: 12, posicion_id: 4)
Jugador.create(nombre: 'MAZZOLA, NICOLAS DARIO', club_id: 12, posicion_id: 4)
Jugador.create(nombre: 'MEDINA, ANTONIO CESAR', club_id: 12, posicion_id: 4)
Jugador.create(nombre: 'MEZA, MAXIMILIANO EDUARDO', club_id: 12, posicion_id: 4)
Jugador.create(nombre: 'RAMIREZ, ERICK IVAN JESUS', club_id: 12, posicion_id: 4)
Jugador.create(nombre: 'VEGETTI, PABLO EZEQUIEL', club_id: 12, posicion_id: 4)

#GODOY CRUZ
#Arqueros
Jugador.create(nombre: 'ALDALLA, ALAN GABRIEL', club_id: 13, posicion_id: 1)
Jugador.create(nombre: 'MOYANO, SEBASTIAN EMANNUEL', club_id: 13, posicion_id: 1)
Jugador.create(nombre: 'RAMIREZ, ROBERTO', club_id: 13, posicion_id: 1)
Jugador.create(nombre: 'REY, RODRIGO FRANCISCO JESUS', club_id: 13, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ALVACETE, JUAN IGNACIO', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'BONACORSO, EZEQUIEL NAHIR', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'BURGOS, ESTEBAN RODRIGO', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'CEBALLOS, LUCAS ESTEBAN', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'CONTRERAS, MATIAS GABRIEL', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'COSARO, GUILLERMO', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'GALEANO, LEONEL EZEQUIEL', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'OLIVAREZ, LEANDRO SEBASTIAN', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'RODRIGUEZ, LUCAS', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'VIERA, DIEGO FRANCISCO', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'VISAGUIRRE, MAURO LEANDRO', club_id: 13, posicion_id: 2)
Jugador.create(nombre: 'ZARATE, NAHUEL ALEJANDRO', club_id: 13, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ANGILERI, FABRICIO GERMAN', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'BURGOA, GONZALO', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'DE FARIAS, LUIS', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'DIAZ, AGUSTIN', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'GARCIA, EMANUEL DAVID', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'GIMENEZ, GASTON CLAUDIO', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'GONZALEZ, DANIEL ALBERTO', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'GONZALEZ, ANGEL', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'ILLANES, FEDERICO ARTURO', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'JEREZ SILVA, LUIS VICENTE', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'MOYANO, GABRIEL OSCAR', club_id: 13, posicion_id: 3)
Jugador.create(nombre: 'ZUQUI, FERNANDO', club_id: 13, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'AYOVI, JAIME JAVIER', club_id: 13, posicion_id: 4)
Jugador.create(nombre: 'BRICO, FERNANDO', club_id: 13, posicion_id: 4)
Jugador.create(nombre: 'CARUSO, LEANDRO RUBEN', club_id: 13, posicion_id: 4)
Jugador.create(nombre: 'CORREA, JAVIER MARCELO', club_id: 13, posicion_id: 4)
Jugador.create(nombre: 'FERNANDEZ, LEANDRO MIGUEL', club_id: 13, posicion_id: 4)
Jugador.create(nombre: 'GARRO, JUAN FERNANDO', club_id: 13, posicion_id: 4)
Jugador.create(nombre: 'MERCADO, KEVIN BRYAN', club_id: 13, posicion_id: 4)

#HURACÁN
#Arqueros
Jugador.create(nombre: 'DIAZ, MARCOS GUILLERMO', club_id: 14, posicion_id: 1)
Jugador.create(nombre: 'FEMIA, LUCAS DANIEL', club_id: 14, posicion_id: 1)
Jugador.create(nombre: 'GIORDANO, MATIAS FEDERICO', club_id: 14, posicion_id: 1)
Jugador.create(nombre: 'MARINELLI, GONZALO', club_id: 14, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ARANO, CARLOS ANDRES', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'BALBI, LUCIANO DAMIAN', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'BLAZQUEZ, MATIAS JAVIER', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'CARRERA, SANTIAGO NICOLAS', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'DOMINGUEZ, EDUARDO RODRIGO', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'ECHEVERRIA, SANTIAGO', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'FERRERO, ALEXIS JAVIER', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'MANCINELLI, FEDERICO', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'NERVO, HUGO MARTIN', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'SOTELO, GUILLERMO', club_id: 14, posicion_id: 2)
Jugador.create(nombre: 'ZARAGOZA, LEONARDO FACUNDO', club_id: 14, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BOGADO, MAURO EZEQUIEL', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'BRUNA, PABLO NICOLAS', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'DISTEFANO, DAVID ANDRES', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'FAVALLI, LUCAS GABRIEL', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'GALLEGOS, EZEQUIEL ADRIAN', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'MANDARINO, GERMAN', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'MONTENEGRO, DANIEL GASTON', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'MORENO Y FABIANESI, IVAN DIEGO', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'NIETO, FEDERICO LUCIANO', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'ROBLEDO, GABRIEL ALEJANDRO', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'ROMERO GAMARRA, ALEJANDRO', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'SARRAFIORE, MARTIN NICOLAS', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'TORANZO, PATRICIO DANIEL', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'VILLARRUEL, LUCAS', club_id: 14, posicion_id: 3)
Jugador.create(nombre: 'VISMARA, FEDERICO', club_id: 14, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ABILA, RAMON DARIO', club_id: 14, posicion_id: 4)
Jugador.create(nombre: 'BORGHELLO, IVAN EMILIO', club_id: 14, posicion_id: 4)
Jugador.create(nombre: 'CAMPANA, LUCAS', club_id: 14, posicion_id: 4)
Jugador.create(nombre: 'ESPINOZA, CRISTIAN OMAR', club_id: 14, posicion_id: 4)
Jugador.create(nombre: 'GIL CLAROTTI, AGUSTIN', club_id: 14, posicion_id: 4)
Jugador.create(nombre: 'ORIETA, MATIAS FABIAN', club_id: 14, posicion_id: 4)
Jugador.create(nombre: 'PUCH, EDSON RAUL', club_id: 14, posicion_id: 4)
Jugador.create(nombre: 'TORASSA, AGUSTIN GONZALO', club_id: 14, posicion_id: 4)

#INDEPENDIENTE
#Arqueros
Jugador.create(nombre: 'DAFFONCHIO, FACUNDO ANDRES', club_id: 15, posicion_id: 1)
Jugador.create(nombre: 'MONTOYA, MARCELO GERMAN', club_id: 15, posicion_id: 1)
Jugador.create(nombre: 'REHAK, GONZALO', club_id: 15, posicion_id: 1)
Jugador.create(nombre: 'RODRIGUEZ, DIEGO MARTIN', club_id: 15, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'AGUILERA, VICTOR EMANUEL', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'BARRIOS, RAFAEL VICTORIANO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'BREITENBRUCH, NESTOR ADRIAL', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'CUESTA, VICTOR LEANDRO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'FIGAL, JORGE NICOLAS', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'ONRAITA, FACUNDO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'PAPA, EMILIANO RAMIRO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'REAL, FEDERICO NICOLAS', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'TAGLIAFICO, NICOLAS ALEJANDRO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'TOLEDO, GUSTAVO ARIEL', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'TULA, CRISTIAN ALBERTO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'VALLES, GABRIEL GUSTAVO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'VICTORINO, MAURICIO BERNARDO', club_id: 15, posicion_id: 2)
Jugador.create(nombre: 'ZARATE, ALEXIS JOEL', club_id: 15, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AQUINO, CLAUDIO EZEQUIEL', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'BELLOCQ, FRANCO', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'GRACIANI, GABRIEL MAXIMILIANO', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'MANCUELLO, FEDERICO ANDRES', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'MENDEZ, JESUS DAVID JOSE', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'NELLE, SAUL SADAM', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'ORTIZ, CRISTIAN JONATAN', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'PISANO, MATIAS', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'RODRIGUEZ, DIEGO MARTIN', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'VILLALBA, LUCAS HERNAN', club_id: 15, posicion_id: 3)
Jugador.create(nombre: 'VITALE, JULIAN', club_id: 15, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ALBERTENGO, LUCAS GABRIEL', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'BENITEZ, MARTIN NICOLAS', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'CAÑETE, JONATAN JOSE', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'DENIS, EZEQUIEL ALEXANDER', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'GOMEZ, WILSON', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'LUCERO, JUAN MARTIN', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'PIZZINI, FRANCISCO ANDRES', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'RIAÑO, CLAUDIO MAXIMILIANO', club_id: 15, posicion_id: 4)
Jugador.create(nombre: 'VALENCIA, JOSE ADOLFO', club_id: 15, posicion_id: 4)

#LANÚS
#Arqueros
Jugador.create(nombre: 'ACOSTA, OSCAR AIN', club_id: 16, posicion_id: 1)
Jugador.create(nombre: 'AVELLANEDA, NICOLAS GASTON', club_id: 16, posicion_id: 1)
Jugador.create(nombre: 'IBAÑEZ, MATIAS ALEJANDRO', club_id: 16, posicion_id: 1)
Jugador.create(nombre: 'MONETTI, FERNANDO', club_id: 16, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ARAUJO, CARLOS LUCIANO', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'BARISONE, DIEGO FRANCISCO', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'BARRIOS, EVER IVAN', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'BRAGHIERI, DIEGO LUIS', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'GOMEZ, GUSTAVO FABIAN', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'MONTESEIRIN, FACUNDO DANIEL', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'ORTIZ, ENZO GABRIEL', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'PASQUINI, NICOLAS', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'SILVA, ALEJANDRO DANIEL', club_id: 16, posicion_id: 2)
Jugador.create(nombre: 'VELAZQUEZ, MAXIMILIANO NICOLAS', club_id: 16, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ACOSTA, LAUTARO GERMAN', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'AGUIRRE, NICOLAS DIEGO', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'AYALA, VICTOR HUGO', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'BARRIENTOS, FERNANDO OMAR', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'BENITEZ, OSCAR JUNIOR', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'FRITZLER, MATIAS LIONEL', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'GALLARDO, WALTER HERNAN', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'IBAÑEZ, JOAQUIN BAUTISTA', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'JAIME, JUAN MIGUEL', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'LETO, SEBASTIAN EDUARDO', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'ORTIZ, JORGE ALBERTO', club_id: 16, posicion_id: 3)
Jugador.create(nombre: 'VALDEZ, JORGE VIDAL', club_id: 16, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ASTINA, MARCOS EMANUEL', club_id: 16, posicion_id: 4)
Jugador.create(nombre: 'BAILONE, IGNACIO DANIEL', club_id: 16, posicion_id: 4)
Jugador.create(nombre: 'DI RENZO, GONZALO IGNACIO', club_id: 16, posicion_id: 4)
Jugador.create(nombre: 'GONZALEZ, SERGIO FABIAN', club_id: 16, posicion_id: 4)
Jugador.create(nombre: 'GONZALEZ, MATIAS LEONEL', club_id: 16, posicion_id: 4)
Jugador.create(nombre: 'MELANO, LUCAS SANTIAGO', club_id: 16, posicion_id: 4)

#NEWELL'S OLD BOYS
#Arqueros
Jugador.create(nombre: 'DEBIASE, ALEX SEBASTIAN', club_id: 17, posicion_id: 1)
Jugador.create(nombre: 'POCRNJIC, LUCIANO DARIO', club_id: 17, posicion_id: 1)
Jugador.create(nombre: 'UNSAIN, LUIS EZEQUIEL', club_id: 17, posicion_id: 1)
Jugador.create(nombre: 'USTARI, OSCAR ALFREDO', club_id: 17, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BAEZ, GABRIEL', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'CACERES, MARCO ANTONIO', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'CALLEGARIS, STEFANO', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'CASCO, MILTON OSCAR', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'CORVALAN, CLAUDIO GASTON', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'FERNANDEZ, LEANDRO SEBASTIAN', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'LOPEZ, VICTOR RUBEN', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'MARTINEZ, SEBASTIAN RODRIGO', club_id: 17, posicion_id: 2)
Jugador.create(nombre: 'PAZ, NEHUEN MARIO', club_id: 17, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BERNARDELLO, HERNAN DELIO', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'CASTRO, ALEXIS NICOLAS', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'ESCOBAR, FRANCO NICOLAS', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'FARAVELLI, LORENZO ABEL', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'FATTORI, FEDERICO', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'FIGUEROA, VICTOR ALBERTO', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'MATEO, DIEGO', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'NEIRA, JUAN ANGEL', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'ORZAN, HORACIO DE DIOS', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'RODRIGUEZ, MAXIMILIANO PABLO', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'SILVA, IVAN EZEQUIEL', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'TONSO, MARTIN', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'TORRES, CARLOS LEONEL', club_id: 17, posicion_id: 3)
Jugador.create(nombre: 'VILLALBA, HERNAN RAUL', club_id: 17, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'FERTOLI, HECTOR HUGO', club_id: 17, posicion_id: 4)
Jugador.create(nombre: 'FIGUEROA, LEANDRO', club_id: 17, posicion_id: 4)
Jugador.create(nombre: 'FYDRISZEWKY, FRANCISCO DAVID', club_id: 17, posicion_id: 4)
Jugador.create(nombre: 'PONCE, EZEQUIEL', club_id: 17, posicion_id: 4)
Jugador.create(nombre: 'SCOCCO, IGNACIO MARTIN', club_id: 17, posicion_id: 4)
Jugador.create(nombre: 'TEVEZ, MAURICIO ALEJANDRO', club_id: 17, posicion_id: 4)
Jugador.create(nombre: 'VIEYRA, JUAN IGNACIO', club_id: 17, posicion_id: 4)

#NUEVA CHICAGO
#Arqueros
Jugador.create(nombre: 'FIEDRICH, GUILLERMO', club_id: 18, posicion_id: 1)
Jugador.create(nombre: 'LANZILLOTA, FEDERICO', club_id: 18, posicion_id: 1)
Jugador.create(nombre: 'SANCHEZ, ALEJANDRO MIGUEL', club_id: 18, posicion_id: 1)
Jugador.create(nombre: 'TAUBER, NICOLAS', club_id: 18, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ACEVEDO, LUCAS JAVIER', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'ARIAS, MAURICIO ANTONIO', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'AVELDAÑO, LUCAS ELIO', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'CABALLERO, LEANDRO AGUSTO', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'CABALLERO, DIEGO MARTIN', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'CORREA, PABLO MARTIN', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'ESPINDOLA, RODRIGO FEDERICO', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'GALARZA, MARCOS ADRIAN', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'MASUERO, ABEL LUIS', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'MONTEAGUDO, JUAN CRUZ', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'SAINZ, NICOLAS MIGUEL', club_id: 18, posicion_id: 2)
Jugador.create(nombre: 'SCHENONE, THOMAS PAUL', club_id: 18, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AQUINO, RODOLFO ANTONIO', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'BENAVIDEZ, EXEQUIEL EMANUEL', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'DE LA FUENTE, FERNANDO EMMANUEL', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'GAGLIARDI, ALEJANDRO FABIAN', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'GIMENEZ, NICOLAS EZEQUIEL', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'GOMEZ, CHRISTIAN GUSTAVO', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'LEMOS, DAMIAN OSCAR', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'PALMIERI, NORBERTO DARIO', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'PANSARDI, FACUNDO NAHUEL', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'PRICHODA, LIHUE DARIO', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'PUCH, MARIANO DAMIAN', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'RAMIREZ, JOSE GABRIEL', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'RUIZ, PABLO MARTIN', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'VERA, MATIAS GABRIEL', club_id: 18, posicion_id: 3)
Jugador.create(nombre: 'VIVAS, GONZALO LEONEL', club_id: 18, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BALDUNCIEL, LUCAS DAVID', club_id: 18, posicion_id: 4)
Jugador.create(nombre: 'DE FEDERICO, MATIAS ADRIAN', club_id: 18, posicion_id: 4)
Jugador.create(nombre: 'GAZALE, DAUD JARED', club_id: 18, posicion_id: 4)
Jugador.create(nombre: 'LENTINI, RAMON ALBERTO', club_id: 18, posicion_id: 4)
Jugador.create(nombre: 'RIZZO, NICOLAS CESAR', club_id: 18, posicion_id: 4)
Jugador.create(nombre: 'SCHWINDT, JESUS', club_id: 18, posicion_id: 4)

#OLIMPO
#Arqueros
Jugador.create(nombre: 'CHAMPAGNE, NEREO', club_id: 19, posicion_id: 1)
Jugador.create(nombre: 'TORRES, IGNACIO NAHUEL', club_id: 19, posicion_id: 1)
Jugador.create(nombre: 'VIOLA, EZEQUIEL', club_id: 19, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'FURIOS, IVAN ALEJANDRO', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'HERRERA, MARCELO LUIS', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'MARTINEZ, ADRIAN NAHUEL', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'MOIRAGHI, NESTOR EMANUEL', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'OROSCO, LUCA EZEQUIEL', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'PARSINARI, OSCAR JONATHAN EZEQUIEL', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'QUIROGA, JUAN LEANDRO', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'SILLS, JUAN IGNACIO', club_id: 19, posicion_id: 2)
Jugador.create(nombre: 'VILLANUEVA, CRISTIAN DAMIAN', club_id: 19, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AMOROSO, JOEL', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'BLANCO, DOMINGO FELIPE', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'BLANCO, JONATHAN MATIAS', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'BOLAÑOS, ALEX LEONARDO', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'COBO GALVEZ, JUAN MANUEL', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'COLACE, HUGO ROBERTO', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'ENCINA, HERNAN NICOLAS', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'MANSILLA, JACOBO GUILLERMO', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'MARTORANO, LEANDRO ESTEBAN', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'PORCARI, MATIAS SEBASTIAN', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'ROYON, PABLO NICOLAS', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'SOSA, DIEGO', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'VEGA, DAVID ALEJANDRO', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'VERA PIRIS, LUCAS LEONEL', club_id: 19, posicion_id: 3)
Jugador.create(nombre: 'VIDAL, MARCELO LEONEL', club_id: 19, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ACOSTA, JOEL GUSTAVO', club_id: 19, posicion_id: 4)
Jugador.create(nombre: 'GAONA LUGO, ORLANDO GABRIEL', club_id: 19, posicion_id: 4)
Jugador.create(nombre: 'KLUSENER, GONZALO MARTIN', club_id: 19, posicion_id: 4)
Jugador.create(nombre: 'NEQUECAUR, LUCIANO', club_id: 19, posicion_id: 4)
Jugador.create(nombre: 'SOÑER, JAVIER DIEGO', club_id: 19, posicion_id: 4)
Jugador.create(nombre: 'TELLAS, GABRIEL CARLOS', club_id: 19, posicion_id: 4)
Jugador.create(nombre: 'VIDAL, NORBERTO EZEQUIEL', club_id: 19, posicion_id: 4)

#QUILMES
#Arqueros
Jugador.create(nombre: 'ASSMANN, WALTER FABIAN', club_id: 20, posicion_id: 1)
Jugador.create(nombre: 'BENITEZ, WALTER DANIEL', club_id: 20, posicion_id: 1)
Jugador.create(nombre: 'DULCICH, SILVIO MARCOS', club_id: 20, posicion_id: 1)
Jugador.create(nombre: 'LEDESMA, MARCOS IGNACIO', club_id: 20, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ALEGRE, ALAN JESUS', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'BONTEMPO, LEONEL JUAN DANIEL', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'CARLI, MANUEL JOEL', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'MALRRECHAUFE, DAMIAN ALEJANDRO', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'MORALES, EMANUEL DAVID', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'NOGUERA, GUSTAVO DAVID', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'SCIFO, ADRIAN MIGUEL', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'SUAREZ, LUCAS MATIAS', club_id: 20, posicion_id: 2)
Jugador.create(nombre: 'UGLESSICH, MARIANO ESTEBAN', club_id: 20, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BRAÑA, RODRIGO', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'BUONANOTTE, DIEGO MARIO', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'CABRERA, NICOLAS ALEJANDRO', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'CALELLO, ADRIAN DANIEL', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'CANELO, ALEXIS PEDRO', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'CARRASCO, GERMAN EMILIANO', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'CASERES, FRANCO EMMANUEL', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'GOMEZ, RODRIGO MANUEL', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'LOPEZ, NICOLAS MAURICIO', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'MORALES, MATIAS OMAR', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'PEREZ GODOY, LUCAS EMMANUEL', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'PEREZ GUEDES, MARTIN', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'ROMERO, SEBASTIAN ARIEL', club_id: 20, posicion_id: 3)
Jugador.create(nombre: 'ZACARIA, JONATHAN FABIAN', club_id: 20, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BIELER, CLAUDIO', club_id: 20, posicion_id: 4)
Jugador.create(nombre: 'DEMELCHORI, LEONEL MAXIMILIANO', club_id: 20, posicion_id: 4)
Jugador.create(nombre: 'FERNANDEZ, ADRIAN NESTOR', club_id: 20, posicion_id: 4)
Jugador.create(nombre: 'HIPPERDINGER, SERGIO GABRIEL', club_id: 20, posicion_id: 4)
Jugador.create(nombre: 'ILARREGUI, FRANCISCO', club_id: 20, posicion_id: 4)
Jugador.create(nombre: 'RAMIREZ, RUBEN DARIO', club_id: 20, posicion_id: 4)

#RACING
#Arqueros
Jugador.create(nombre: 'GOMEZ, GASTON', club_id: 21, posicion_id: 1)
Jugador.create(nombre: 'IBAÑEZ, NELSON MARTIN', club_id: 21, posicion_id: 1)
Jugador.create(nombre: 'MUSSO, JUAN AGUSTIN', club_id: 21, posicion_id: 1)
Jugador.create(nombre: 'SAJA, SEBASTIAN DIEGO', club_id: 21, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BAZAN, MAURO EZEQUIEL', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'CABRAL, YONATHAN EMANUEL', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'CAMPI, GASTON MATIAS', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'DIAZ, RICARDO GASTON', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'GRIMI, LEANDRO DAMIAN MARCELO', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'LOLLO, MAURICIO LUCIANO', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'PILLUD, IVAN ALEXIS', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'SANCHEZ, NICOLAS GABRIEL', club_id: 21, posicion_id: 2)
Jugador.create(nombre: 'VOBORIL, GERMAN ARIEL', club_id: 21, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ACEVEDO, NELSON FERNANDO', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'ACUÑA, MARCOS JAVIER', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'ALVARADO, PABLO ANDRES', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'AUED, LUCIANO ROMAN', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'BAREIRO, LUCAS MARIANO', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'CAMACHO, FERNANDO WASHINGTON', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'CERRO, FRANCISCO JAVIER', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'NAGUEL, CARLOS SANTIAGO', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'OROZ, NICOLAS ADRIAN', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'ROLHEISER, LEONARDO ENRIQUE', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'ROMERO, OSCAR DAVID', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'VALENZUELA, CARLOS FERNANDO', club_id: 21, posicion_id: 3)
Jugador.create(nombre: 'VIDELA, EZEQUIEL OSCAR', club_id: 21, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BOU, GUSTAVO LEONARDO', club_id: 21, posicion_id: 4)
Jugador.create(nombre: 'CASTILLON, FACUNDO ANDRES', club_id: 21, posicion_id: 4)
Jugador.create(nombre: 'CASTRO, FACUNDO ALFREDO', club_id: 21, posicion_id: 4)
Jugador.create(nombre: 'FERNANDEZ, BRIAN', club_id: 21, posicion_id: 4)
Jugador.create(nombre: 'MILITO, DIEGO ALBERTO', club_id: 21, posicion_id: 4)
Jugador.create(nombre: 'NUÑEZ, CARLOS RODRIGO', club_id: 21, posicion_id: 4)
Jugador.create(nombre: 'PAVONE, HUGO MARIANO', club_id: 21, posicion_id: 4)
Jugador.create(nombre: 'RESCALDANI, EZEQUIEL', club_id: 21, posicion_id: 4)

#RIVER PLATE
#Arqueros
Jugador.create(nombre: 'BAROVERO, MARCELO ALBERTO', club_id: 22, posicion_id: 1)
Jugador.create(nombre: 'BATALLA, AUGUSTO MARTIN', club_id: 22, posicion_id: 1)
Jugador.create(nombre: 'CHIARINI, JULIO CESAR', club_id: 22, posicion_id: 1)
Jugador.create(nombre: 'FRANCESE, NICOLAS', club_id: 22, posicion_id: 1)
Jugador.create(nombre: 'RODRIGUEZ, NICOLAS FABIAN', club_id: 22, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ALVAREZ BALANTA, EDER FABIAN', club_id: 22, posicion_id: 2)
Jugador.create(nombre: 'FUNES MORI, JOSE RAMIRO', club_id: 22, posicion_id: 2)
Jugador.create(nombre: 'MAIDANA, JONATHAN RAMON', club_id: 22, posicion_id: 2)
Jugador.create(nombre: 'MAMMANA, EMANUEL HERNAN', club_id: 22, posicion_id: 2)
Jugador.create(nombre: 'MERCADO, GABRIEL IVAN', club_id: 22, posicion_id: 2)
Jugador.create(nombre: 'PEZZELA, GERMAN ALEJO', club_id: 22, posicion_id: 2)
Jugador.create(nombre: 'VEGA, LEANDRO SEBASTIAN', club_id: 22, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AIMAR, PABLO CESAR', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'BERTOLO, NICOLAS SANTIAGO', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'CIRIGLIANO, ANDRES EZEQUIEL', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'GONZALEZ, LUIS OSCAR', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'KRANEVITTER, CLAUDIO MATIAS', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'MARTINEZ, GONZALO NICOLAS', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'MARTINEZ, TOMAS', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'MAYADA, CAMILO SEBASTIAN', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'PISCULICHI, LEONARDO NICOLAS', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'PONZIO, LEONARDO DANIEL', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'RODRIGUEZ, GUIDO', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'SANCHEZ, CARLOS ANDRES', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'SOLARI, AUGUSTO JORGE MATEO', club_id: 22, posicion_id: 3)
Jugador.create(nombre: 'VANGIONI, LEONEL JESUS', club_id: 22, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ALARIO, LUCAS DAMIAN', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'ANDRADA, FEDERICO OSCAR', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'BOYE, LUCAS ARIEL', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'CAVENAGHI, FERNANDO EZEQUIEL', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'DRIUSSI, SEBASTIAN', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'GUTIERREZ, TEOFILO ANTONIO', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'KRAPOF, JUAN CRUZ', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'LOPEZ, FRANCO ALEXIS', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'MORA, RODRIGO NICANOR', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'SAVIOLA, JAVIER PEDRO', club_id: 22, posicion_id: 4)
Jugador.create(nombre: 'SIMEONE, GIOVANNI PABLO', club_id: 22, posicion_id: 4)

#ROSARIO CENTRAL
#Arqueros
Jugador.create(nombre: 'CARANTA, MAURICIO ARIEL', club_id: 23, posicion_id: 1)
Jugador.create(nombre: 'DI FULVIO, EMILIO', club_id: 23, posicion_id: 1)
Jugador.create(nombre: 'LEDESMA, JEREMIAS CONAN', club_id: 23, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ALARCON, FERNANDO RUBEN', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'ALVAREZ, PABLO SEBASTIAN', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'ANDRADA, EMANUEL EZEQUIEL', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'BERRA, TOMAS', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'DONATTI, ALEJANDRO CESAR', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'FARA, CAIN JAIR', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'FERRARI, PAULO ANDRES', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'FERRARI, JONATHAN MARCELO', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'GOMEZ, ELIAS JOSE', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'GOMEZ, YEIMAR PASTOR', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'HERRANZ, NICOLAS JOSE', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'PIÑERO, FERNANDO', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'PINOLA, HORACIO JAVIER', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'SALAZAR, VICTOR EZEQUIEL', club_id: 23, posicion_id: 2)
Jugador.create(nombre: 'VILLAGRA, CRISTIAN CARLOS', club_id: 23, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AGUIRRE AVALOS, LEONEL JONAS', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'BECKER, PABLO IGNACIO', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'CERVI, FRANCO EMANUEL', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'COLMAN, GUSTAVO ALEJANDRO', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'DA CAMPO, HERNAN NICOLAS', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'DOMINGUEZ, NERY ANDRES', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'FARED, JESUS ALFREDO', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'FERNANDEZ, JOSE LUIS', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'FLORES, FEDERICO JESUS', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'GONZALEZ, MAXIMILIANO DAVID', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'LO CELSO, GIOVANI', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'MARTINICH, MARCOS DANIEL', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'MONTOYA, WALTER IVAN', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'MUSTO, DAMIAN MARCELO', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'PALMA, GASTON DARIO', club_id: 23, posicion_id: 3)
Jugador.create(nombre: 'ZABALA, BRUNO ALBERTO', club_id: 23, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ACUÑA, WALTER RUBEN', club_id: 23, posicion_id: 4)
Jugador.create(nombre: 'DELGADO, CESAR RAMON', club_id: 23, posicion_id: 4)
Jugador.create(nombre: 'MIGONE, RODRIGO JAVIER', club_id: 23, posicion_id: 4)
Jugador.create(nombre: 'NIELL, FRANCO', club_id: 23, posicion_id: 4)
Jugador.create(nombre: 'OVIEDO, FRANCO', club_id: 23, posicion_id: 4)
Jugador.create(nombre: 'PROTTI, IJIEL CESAR', club_id: 23, posicion_id: 4)
Jugador.create(nombre: 'RUBEN, MARCO GASTON', club_id: 23, posicion_id: 4)

#SAN LORENZO
#Arqueros
Jugador.create(nombre: 'DEVECCHI, JOSE ANTONIO', club_id: 24, posicion_id: 1)
Jugador.create(nombre: 'TORRICO, SEBASTIAN ALBERTO', club_id: 24, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ARIAS, RAMIRO EZEQUIEL', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'BUFFARINI, JULIO ALBERTO', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'CARDONA, TOAMS', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'CARUZZO, MATIAS NICOLAS', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'CATALAN, MATIAS EZEQUIEL', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'CETTO, MAURO DARIO JESUS', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'FONTANINI, FABRICIO BAUTISTA', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'MAS, EMANUEL MATIAS', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'PROSPERI, GONZALO SEBASTIAN', club_id: 24, posicion_id: 2)
Jugador.create(nombre: 'YEPES, MARIO ALBERTO', club_id: 24, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AVILA, LUIS EZEQUIEL', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'BARBARO, ALEJANDRO BRIAN', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'BARRIENTOS, PABLO CESAR', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'BLANCO, SEBASTIAN MARCELO', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'KALINSKI, ENZO MAXIMILIANO', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'MERCIER, JUAN IGNACIO', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'MUSSIS, FRANCO GABRIEL', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'NAVARRO, LEANDRO ALEXIS', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'ORTIGOZA, NESTOR EZEQUIEL', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'QUIGNON, FACUNDO TOMAS', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'ROMAGNOLI, LEANDRO ATILIO', club_id: 24, posicion_id: 3)
Jugador.create(nombre: 'RUIZ, ALAN NAHUEL', club_id: 24, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CAUTERUCCIO, MARTIN', club_id: 24, posicion_id: 4)
Jugador.create(nombre: 'MATOS, MAURO', club_id: 24, posicion_id: 4)
Jugador.create(nombre: 'MONTAGNA, EZEQUIEL', club_id: 24, posicion_id: 4)
Jugador.create(nombre: 'VERON, GONZALO ALBERTO', club_id: 24, posicion_id: 4)
Jugador.create(nombre: 'VILLALBA, HECTOR DANIEL', club_id: 24, posicion_id: 4)

#SAN MARTÍN SAN JUAN
#Arqueros
Jugador.create(nombre: 'ARDENTE, LUIS EMANUEL', club_id: 25, posicion_id: 1)
Jugador.create(nombre: 'CORTI, LEONARDO ANDRES', club_id: 25, posicion_id: 1)
Jugador.create(nombre: 'URRABURU, FEDERICO DAMIAN', club_id: 25, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'CAPELLI, JAVIER ALEJANDRO', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'CARNIELLO, OSCAR MATIAS', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'FRANCO, DANIEL ALEJANDRO', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'GOMEZ, JOSE LUIS', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'IBERBIA, RAUL ALEJANDRO', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'JOFRE, LUCAS NAHUEL', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'LEDESMA, DAMIAN DAVID', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'MATTIA, JUAN FRANCISCO', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'PINTOS, MARCOS ARIEL', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'SILVA, MATIAS', club_id: 25, posicion_id: 2)
Jugador.create(nombre: 'VERA, GONZALO RENZO', club_id: 25, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'BUSTOS, MAXIMILIANO ANDRES', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'CANUHE, CRISTIAN EZEQUIEL', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'COVEA, MICHAEL ONEIL', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'FISSORE, MATIAS OSCAR', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'GELABERT, MARCOS AGUSTIN', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'JONES, MATIAS GUSTAVO', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'LOPEZ, RAMIRO ANDRES', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'MILANO, MAURO RAMIRO', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'PELAITAY, NICOLAS', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'QUIROGA, RAUL ALBERTO', club_id: 25, posicion_id: 3)
Jugador.create(nombre: 'SALAS, LUCAS EZEQUIEL', club_id: 25, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'ALANIZ, RODRIGO', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'APARICIO, ERIC DANIEL', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'BUENO, CARLOS EBER', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'CABALLERO, FRANCO JAVIER', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'FIGUEROA, MARCOS DANIEL', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'MARTINEZ, LEANDRO', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'NAVARRO, ALVARO DAMIAN', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'PINEDO, GUSTAVO', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'PUMPIDO, FACUNDO', club_id: 25, posicion_id: 4)
Jugador.create(nombre: 'VITTI, PABLO ERNESTO', club_id: 25, posicion_id: 4)

#SARMIENTO
#Arqueros
Jugador.create(nombre: 'BANGARDINO, PABLO MARTIN', club_id: 26, posicion_id: 1)
Jugador.create(nombre: 'RIGAMONTI, CESAR PABLO', club_id: 26, posicion_id: 1)
Jugador.create(nombre: 'VICENTINI, MANUEL MATIAS', club_id: 26, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'AGUILAR, PABLO ANDRES', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'CANTO, GUSTAVO DAMIN', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'CASIERRA, MAURICIO FERNEY', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'CORIA, FRANCO', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'DELGADO, DANIEL ALBERTO', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'DUTARI, FRANCISCO', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'ESPINAZO, GERMAN', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'LUNA, SEBASTIAN', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'MENDEZ, MAXIMIIANO', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'PEPPINO, FRANCO', club_id: 26, posicion_id: 2)
Jugador.create(nombre: 'QUIROGA, MARIO NAHUEL', club_id: 26, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AZIL, JUAN MANUEL', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'DIAZ, MATIAS IGNACIO', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'IUVALE, SILVIO OSCAR', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'LOPEZ, IGNACIO JOSE', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'MELO, EDUARDO ALEJANDRO', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'MILOC, DARDO FEDERICO', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'NUÑEZ, GERVASIO DANIEL', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'PASCUCCI, AGUSTIN', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'QUIROGA, LUIS OSCAR', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'SANCHEZ, NICOLAS ANDRES', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'SCATOLARO, MARCELO ANDRES', club_id: 26, posicion_id: 3)
Jugador.create(nombre: 'SPINACCI, RENZO', club_id: 26, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CACHEIRO, IGNACIO ANDRES', club_id: 26, posicion_id: 4)
Jugador.create(nombre: 'CASTRO, FEDERICO GASTON', club_id: 26, posicion_id: 4)
Jugador.create(nombre: 'CUEVAS, HECTOR LUIS', club_id: 26, posicion_id: 4)
Jugador.create(nombre: 'FIGUEROA, TOBIAS NAHUEL', club_id: 26, posicion_id: 4)
Jugador.create(nombre: 'FORNARIS, MAXIMILIANO', club_id: 26, posicion_id: 4)
Jugador.create(nombre: 'VIVANI, JOAQUIN', club_id: 26, posicion_id: 4)

#TEMPERLEY
#Arqueros
Jugador.create(nombre: 'CRIVELLI, FEDERICO', club_id: 27, posicion_id: 1)
Jugador.create(nombre: 'DE BORTOLI, LEANDRO', club_id: 27, posicion_id: 1)
Jugador.create(nombre: 'GARCIA, RODRIGO', club_id: 27, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'AGUIRRE, GASTON DAMIAN', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'BARRIOS, LEONEL', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'BOGGINO, IGNACIO', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'BOJANICH, GASTON DARIO', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'CHIMINO, CHRISTIAN', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'GONZALEZ, FERNANDO JAVIER', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'PAZ, CRISTIAN IGNACIO', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'ROMERO, PATRICIO NICOLAS', club_id: 27, posicion_id: 2)
Jugador.create(nombre: 'RUIZ, ENZO ADRIAN', club_id: 27, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'APRILE, GUSTAVO JAVIER', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'ARREGUI, ADRIAN', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'BRANDAN, FERNANDO DANIEL', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'BRUNO, FEDERICO RUBEN', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'DI LORENZO, LEONARDO', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'ESPARZA, CRISTIAN GABRIEL', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'LEDESMA, EDUARDO FABIAN', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'MAGALLAN, SANTIAGO', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'ORONA, IGNACIO', club_id: 27, posicion_id: 3)
Jugador.create(nombre: 'SAMBUEZA, FABIAN HECTOR', club_id: 27, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'DINNENO, JUAN IGNACIO', club_id: 27, posicion_id: 4)
Jugador.create(nombre: 'GRBEC, JAVIER ANTONIO', club_id: 27, posicion_id: 4)
Jugador.create(nombre: 'LOPEZ, LUIS EDUARDO', club_id: 27, posicion_id: 4)
Jugador.create(nombre: 'TERZAGHI, EMILIANO FRANCO', club_id: 27, posicion_id: 4)
Jugador.create(nombre: 'VILCHEZ, PABLO EZEQUIEL', club_id: 27, posicion_id: 4)

#TIGRE
#Arqueros
Jugador.create(nombre: 'D ANGELO, SEBASTIAN EZEQUIEL', club_id: 28, posicion_id: 1)
Jugador.create(nombre: 'GARCIA, JAVIER HERNAN', club_id: 28, posicion_id: 1)
Jugador.create(nombre: 'LUGO, FERNANDO JAVIER', club_id: 28, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BLENGIO, JUAN CARLOS', club_id: 28, posicion_id: 2)
Jugador.create(nombre: 'BONADIO, IGNACIO', club_id: 28, posicion_id: 2)
Jugador.create(nombre: 'ECHEVERRIA, MARIANO RAUL', club_id: 28, posicion_id: 2)
Jugador.create(nombre: 'GODOY, ERIK FERNANDO', club_id: 28, posicion_id: 2)
Jugador.create(nombre: 'GOÑI, ERNESTO', club_id: 28, posicion_id: 2)
Jugador.create(nombre: 'GONZALEZ PIREZ, LEANDRO MARTIN', club_id: 28, posicion_id: 2)
Jugador.create(nombre: 'IZAGUIRRE, SANTIAGO', club_id: 28, posicion_id: 2)
Jugador.create(nombre: 'PANTALEONE, NICOLAS', club_id: 28, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ARZURA, JOAQUIN', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'BERTOGLIO, FACUNDO DANIEL', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'CASTRO, ALEXIS', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'GALMARINI, MARTIN', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'ITABEL, KEVIN FABIAN EMILIANO', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'JANSON, LUCAS EZEQUIEL', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'MENOSSI, LUCAS ARIEL', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'PAGLIALUNGA, MARIO ANGEL', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'PELLETIERI, AGUSTIN DANIEL', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'REDONDO, FERNANDO', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'SANCHEZ, FACUNDO', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'STEGMAN, ALBERTO MARIO CESAR', club_id: 28, posicion_id: 3)
Jugador.create(nombre: 'WILCHES, LUCAS ANTONIO', club_id: 28, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CORREA, JOSE ERIK', club_id: 28, posicion_id: 4)
Jugador.create(nombre: 'GARATE, LEANDRO JULIAN', club_id: 28, posicion_id: 4)
Jugador.create(nombre: 'LARRONDO, MARCELO ALEJANDRO', club_id: 28, posicion_id: 4)
Jugador.create(nombre: 'LUNA, CARLOS ARIEL', club_id: 28, posicion_id: 4)
Jugador.create(nombre: 'RINCON, SEBASTIAN', club_id: 28, posicion_id: 4)

#UNIÓN
#Arqueros
Jugador.create(nombre: 'CASTRO, MATIAS FIDEL', club_id: 29, posicion_id: 1)
Jugador.create(nombre: 'FERNANDEZ, NEREO ARIEL', club_id: 29, posicion_id: 1)
Jugador.create(nombre: 'PAPALEO, JOAQUIN', club_id: 29, posicion_id: 1)
Jugador.create(nombre: 'PEANO, MARCOS FIDEL', club_id: 29, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'BRITEZ, EMANNUEL', club_id: 29, posicion_id: 2)
Jugador.create(nombre: 'CARDOZO, MARCELO ALEJANDRO', club_id: 29, posicion_id: 2)
Jugador.create(nombre: 'FLEITAS, BRIAN JONATAN DAVID', club_id: 29, posicion_id: 2)
Jugador.create(nombre: 'GARCIA, ROLANDO DANIEL', club_id: 29, posicion_id: 2)
Jugador.create(nombre: 'MAIDANA, MAURO ANGEL', club_id: 29, posicion_id: 2)
Jugador.create(nombre: 'SANCHEZ, LEONARDO AGUSTIN', club_id: 29, posicion_id: 2)
Jugador.create(nombre: 'SANDONA, AGUSTIN', club_id: 29, posicion_id: 2)
Jugador.create(nombre: 'ZURBRIGGEN, SANTIAGO', club_id: 29, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'AFFRANCHINO, FACUNDO ANDRES', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'DE IRIONDO, MANUEL IGNACIO', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'ELLACOPULOS, EMILIANO NAHUEL', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'FANTIN, MATIAS ORLANDO', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'FELIPE LISSI, GERONIMO', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'GALLIGO, DIEGO', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'MALCORRA, VICTOR IGNACIO', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'MARTINEZ, MAURICIO', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'MONTERO, FAUSTO EMANUEL', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'RIVAS, JUAN GABRIEL', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'SANCHEZ, MATIAS ARIEL', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'SOLDANO, MAURICIO FRANCO', club_id: 29, posicion_id: 3)
Jugador.create(nombre: 'VILLAR, DIEGO NICOLAS', club_id: 29, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'BOLZICCO, TOMAS', club_id: 29, posicion_id: 4)
Jugador.create(nombre: 'CONIGLIO, FERNANDO', club_id: 29, posicion_id: 4)
Jugador.create(nombre: 'GAMBA, LUCAS EMANUEL', club_id: 29, posicion_id: 4)
Jugador.create(nombre: 'GUERRA, CLAUDIO RUBEN', club_id: 29, posicion_id: 4)
Jugador.create(nombre: 'TARQUINI, JONATHAN', club_id: 29, posicion_id: 4)
Jugador.create(nombre: 'TRIVERIO, ENRIQUE LUIS', club_id: 29, posicion_id: 4)

#VÉLEZ SARSFIELD
#Arqueros
Jugador.create(nombre: 'AGUERRE, ALAN JOAQUIN', club_id: 30, posicion_id: 1)
Jugador.create(nombre: 'FIGUEROA, TOMAS CARLOS', club_id: 30, posicion_id: 1)
Jugador.create(nombre: 'SOSA, CARLOS SEBASTIAN', club_id: 30, posicion_id: 1)
Jugador.create(nombre: 'YORDAN, GONZALO JAVIER', club_id: 30, posicion_id: 1)
#Defensores
Jugador.create(nombre: 'ALANIZ, LUCAS ARIEL', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'AMOR, EMILIANO JAVIER', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'CARDOZO, FACUNDO OMAR', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'CUBERO, FABIAN ALBERTO', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'CUFRE, BRIAN EZEQUIEL', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'DELGADILLO, NICOLAS', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'GIANETTI, LAUTARO DANIEL', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'GRILLO, LAUTARO FAUSTO', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'PELLERANO, HERNAN DARIO', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'PEREZ ACUÑA, MATIAS', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'RIOS, RAMIRO ALEXIS', club_id: 30, posicion_id: 2)
Jugador.create(nombre: 'ROLON, LEONARDO GABRIEL', club_id: 30, posicion_id: 2)
#Volantes
Jugador.create(nombre: 'ALARIO, ALAN CRISTIAN', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'ASAD, YAMIL RODRIGO', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'BELLA, IVAN GONZALO', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'CHACON, IVAN ALFREDO', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'COMPAGNUCCI, LUCIO', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'CORREA, JORGE IVAN', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'DESABATO, LEANDRO LUIS', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'DOFFO, AGUSTIN', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'FERREIRA, BRIAN FEDERICO', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'FERREYRA, GERMAN JULIO CESAR', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'LUCERO, JUAN EMANUEL', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'MARTELLI, SEBASTIAN ALEJANDRO', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'RAMIREZ, MATEO', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'ROMERO, LUCAS DANIEL', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'SOMOZA, LEANDRO DANIEL', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'TRIPICHIO, NICOLAS MARTIN', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'VERA, LEANDRO YOEL', club_id: 30, posicion_id: 3)
Jugador.create(nombre: 'VILLALBA, LEONARDO ENRIQUE', club_id: 30, posicion_id: 3)
#Delanteros
Jugador.create(nombre: 'CARAGLIO, MILTON JOEL', club_id: 30, posicion_id: 4)
Jugador.create(nombre: 'CASERES, RAMIRO JULIAN', club_id: 30, posicion_id: 4)
Jugador.create(nombre: 'NANNI, ROBERTO ANTONIO', club_id: 30, posicion_id: 4)
Jugador.create(nombre: 'TOLEDO, HERNAN DARIO', club_id: 30, posicion_id: 4)
Jugador.create(nombre: 'VAZQUEZ, FEDERICO NAHUEL', club_id: 30, posicion_id: 4)
Jugador.create(nombre: 'VELEZ, JOSE DAVID', club_id: 30, posicion_id: 4)